[build]
builder = "NIXPACKS"
buildCommand = "npm run build && typeorm-ts-node-commonjs migration:run -d dist/src/data-source.js"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10